--- #YAML:1.0
name:               Date-Chinese
version:            1.12
abstract:           Calculate dates in the Chinese calendar
author:
    - Rich Bowen (rbowen@rcbowen.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
